"""Build a synthetic panel with the real V9 deployment schema, so
measure_lookahead_bias.py can be exercised end-to-end before dell runs it
against the 6.4M-row file on Drive.

FIXTURE FORMAT -- why this takes an --out path instead of hardcoding parquet
    This file used to end with an unconditional
        out.to_parquet('/tmp/j/fake_V9.parquet', engine='pyarrow', ...)
    which could not run in the verification sandbox at all: there is no pyarrow
    here, and /tmp/j did not exist either. Meanwhile run_measure_test.py -- the
    driver written to exercise measure_lookahead_bias.py -- monkey-patches
    pd.read_parquet to pd.read_pickle and therefore wants a PICKLE. So the
    fixture builder and the fixture consumer disagreed on format, and the pair
    never composed. Consequence: measure_lookahead_bias.py had never actually
    been run end-to-end in this sandbox, only `--help`-ed -- and it is step 1 of
    the runbook. Found 2026-08-22.

    Now the writer is chosen from the extension and the parent directory is
    created, so the default `python3 make_fake_v9.py` works with no arguments
    and no pyarrow. Pass a .parquet path to get a real parquet where pyarrow
    exists (Colab does have it); the schema written is identical either way.
"""
import argparse
import os
import sys

import numpy as np
import pandas as pd

sys.path.insert(0, '.')
from coiled_alpha_logic import apply_coiled_alpha_logic

ap = argparse.ArgumentParser()
ap.add_argument('--out', default='/tmp/j/fake_V9.pkl',
                help='.pkl/.pickle -> to_pickle; .parquet -> to_parquet (needs pyarrow)')
args = ap.parse_args()

RNG = np.random.default_rng(3)
N_DAYS, N_SYMS = 900, 40
dates = pd.bdate_range('2021-01-01', periods=N_DAYS)

rows = []
for s in range(N_SYMS):
    sym, px = f'SYM{s:03d}', 100.0 + s * 11
    for i, d in enumerate(dates):
        base = 0.012 + (s % 6) * 0.004
        vol = base * (0.5 if (i % 180) > 140 and s % 3 == 0 else 1.0)
        ret = (0.0003 + (s % 7) * 0.00035) + RNG.normal(0, vol)
        prev = px
        px = max(1.0, px * (1 + ret))
        o = prev * (1 + RNG.normal(0, vol * 0.4))
        rows.append({'DATE': d, 'SYMBOL': sym, 'OPEN': o,
                     'HIGH': max(o, px) * (1 + abs(RNG.normal(0, vol * 0.4))),
                     'LOW': min(o, px) * (1 - abs(RNG.normal(0, vol * 0.4))),
                     'CLOSE': px,
                     'VOLUME': (300_000 + s * 90_000) * (1 + abs(RNG.normal(0, 0.2)))})
raw = pd.DataFrame(rows)
nifty = (raw.groupby('DATE', as_index=False)['CLOSE'].mean()
         .rename(columns={'CLOSE': 'NIFTY_CLOSE'}))

# Build the CONTAMINATED parquet, i.e. what dell has on Drive today:
# generated by the UNPATCHED module, so BB_Enter_Today is unlagged.
df = apply_coiled_alpha_logic(raw, nifty_df=nifty, lag_sniper_decision_inputs=False)

df['MR_Base_Signal'] = False
df['SMA_5'] = df.groupby('SYMBOL')['CLOSE'].transform(lambda x: x.rolling(5).mean())
df['Regime_Label'] = 'BULL'
df['VIX_Spike'] = False
df['Systemic_Panic'] = False

cols = ['DATE', 'SYMBOL', 'OPEN', 'HIGH', 'LOW', 'CLOSE',
        'Daily_Turnover_Rank', 'Turnover_SMA_50', 'Market_Breadth', 'Target_ATR',
        'BB_Enter_Today', 'BB_Exhaustion_Today', 'MR_Base_Signal', 'SMA_5',
        'RS_Percentile', 'ATR_Contraction_Ratio',
        'Regime_Label', 'VIX_Spike', 'Systemic_Panic']
out = df[cols].copy()
# drop the diagnostic column so the fixture matches a pre-patch parquet exactly
assert 'BB_Enter_Signal_Raw' not in out.columns

dest = args.out
os.makedirs(os.path.dirname(os.path.abspath(dest)), exist_ok=True)
ext = os.path.splitext(dest)[1].lower()
if ext in ('.pkl', '.pickle'):
    out.to_pickle(dest)
elif ext == '.parquet':
    out.to_parquet(dest, engine='pyarrow', compression='snappy')
else:
    sys.exit(f"Unrecognised extension {ext!r} -- use .pkl or .parquet")

print(f"Wrote {dest}  {len(out):,} rows, "
      f"{out['SYMBOL'].nunique()} symbols, signals={int(out['BB_Enter_Today'].sum())}")
print("Columns:", list(out.columns))
